* semenInRussia emacs configration

** Features

- a beautiful design.

  It includes
  + a big amount of themes
  + diagnostics and other things from echo area at the top left corner
  + amazing modeline
  + icons everywhere
  + No to ~prettify-mode~
  + Small, but amazing paddings around screen

- Very (really very) fast start up.

  On my old computer ~doomemacs~ starts in 4+ seconds (it prints it after startup), but in fact it also wait for when themes, modeline and other things will be loaded.  My config on other side take only 2secs and almost don't take time after.

- A big amount of packages (192+)

- ~meow~ over ~evil~

- Own package manager, built over ~straight.el~.

  The benefit is a speed, it only one time add to the a path ~load-path~.  And other times Emacs will find a package only in this directory, instead of 220+ other dirs when use ~straight.el~

- Use good-practice solutions, like replace heavy things with the more light.

- Use ~perspectives~ (vertual desktops/workspaces for Emacs) with intuitive way


** Installiation

This Emacs configuration have the most fast way to install (if consider amount of 3rd party packages), to install this config you need to download a zip-archive from [[https://github.com/semenInRussia/emacs.el/actions][actions tab]] and extract an archive into any directory.

You can extract an archive into any directory, and run emacs using ~--init-directory~ flag, like:

#+BEGIN_SRC shell
emacs --init-directory=~/semacs
#+END_SRC

So you can test it without ~chemacs~ and other stupid things
