name: Build ZIP from built 3rd party packages and byte-compiled config
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Emacs
        uses: purcell/setup-emacs@master
        with:
          version: snapshot
      - name: Clone the Config
        uses: actions/checkout@v3
      - name: Install All Emacs Packages and Build Config
        run: emacs -batch -l init.el --install --local-projets --modules
      - name: Create an Archive
        run: tar -czf semacs.zip lisp pam cows dist init.el init.elc early-init.el early-init.elc small-init.el snippets .githignore .github
      - name: Publish an Archive
        id: archive
        uses: elgohr/Github-Release-Action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          title: dok
