name: Build ZIP from built 3rd party packages and byte-compiled config
run-name: publish ZIP to releases
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: purcell/setup-emacs@master
        with:
          version: 29.1
      - uses: actions/checkout@v3
      - run: emacs --install --local-projets --modules
