name: Build ZIP from built 3rd party packages and byte-compiled config
run-name: publish ZIP to releases
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: purcell/setup-emacs@master
        with:
          version: 29.1
      - uses: actions/checkout@v3
      - run: emacs --install --local-projets --modules --kill
      - run: tar -czf semacs.zip lisp pam cows dist init.el init.elc early-init.el early-init.elc small-init.el snippets .githignore .github
      - name: Create an Archive
        id: archive
        uses: elgohr/Github-Release-Action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          title: dok
