name: Do a first Emacs call and Create the zip-archive from generated files
on: [push]

jobs:
  zip:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Emacs
        uses: purcell/setup-emacs@master
        with:
          version: 29.1

      - name: Clone the Config
        uses: actions/checkout@v3

      - name: Do a First Emacs Call
        run: emacs -batch -l init.el --install --local-projets --modules

      - name: Release the New Config Version
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Built Emacs Config"
          files: |
            .github
            cows
            lisp
            snippets
            .gitignore
            early-init.el
            init.el
            README.org
            small-init.el
