name: Do a first Emacs call and Create the zip-archive from generated files
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Emacs
        uses: purcell/setup-emacs@master
        with:
          version: snapshot

      - name: Clone the Config
        uses: actions/checkout@v3

      - name: Do a First Emacs Call
        run: emacs -batch -l init.el --install --local-projets --modules

      - name: Create the Archive from Generated Files
        run: tar -czf semacs.zip lisp pam cows dist init.el early-init.el small-init.el snippets .gitignore .github

      - name: Upload the Archive
        id: archive
        uses: elgohr/Github-Release-Action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          title: dok
