name: Do a first Emacs call and Create the zip-archive from generated files
on: [push]

jobs:
  zip:
    runs-on: manjaro-latest

    steps:
      - name: Setup Emacs
        uses: purcell/setup-emacs@master
        with:
          version: 29.1

      - name: Clone the Config
        uses: actions/checkout@v3

      - name: Do a First Emacs Call
        run: emacs -batch -l init.el --install --local-projets --modules

      - name: Create the Archive from Generated Files
        run: zip -r semacs.zip lisp pam cows dist init.el early-init.el small-init.el snippets .gitignore .github

      - name: Upload the Archive
        id: archive
        uses: actions/upload-artifact@v3
        with:
          name: semacs
          path: semacs.zip
