name: Do a first Emacs call and Create the zip-archive from generated files
on: [push]

jobs:
  zip:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Emacs
        uses: purcell/setup-emacs@master
        with:
          version: 29.1

      - name: Clone the Config
        uses: actions/checkout@v3

      - name: Do a First Emacs Call
        run: emacs -batch -l init.el --install --local-projets --modules

      - name: Create the Archive from Generated Files
        run: zip -r semacs.zip lisp pam cows dist init.el early-init.el small-init.el README.org snippets .git .gitignore .github

      - name: Release the New Config Version
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: latest
          files: semacs.zip
